Rachel/nav bar
SheCodesAus/2024_a_dynamic_array_frontend pull request #62
Opened 2024-04-02 11:34 UTC by blakerach1

## Describe your changes

Conditionally rendering the NAV bar so that an admin user will have access to a list of users, a user will have access to their account and a profile owner will have access to their profile.

## Type of change

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## What kind of feedback do you need?

Quick look

## Checklist:

- [x] I have performed a self-review of my code
- [x] I have recommended where to start and how to proceed with the review
- [x] I have done a git pull from DEV to ensure this PR is up to date

2024-04-02 12:01 UTC, ktechgau approved these changes

2024-04-02 23:10 UTC, shayzimm approved these changes

2024-04-02 23:58 UTC, Lyndallh requested changes

2024-04-02 23:58 UTC, Lyndallh commented on src/components/NavBar/NavBar.jsx
I think there is an issue with the admin conditional, I can see the user admin link regardless of my authentication

See below image - you can see I am logged out (because I can see the Login link) and I can also see the Admin User link. 
<img width="423" alt="image" src="https://github.com/SheCodesAus/2024_a_dynamic_array_frontend/assets/16198398/0e1c8377-c2f6-4f1b-9ed4-4942bfe83643">

Has profile on line 82 is also not working correctly as my user did not have a profile and I was navigated to http://localhost:5174/profile/undefined which rendered . I don't know is that is because the profiles page is not functional yet though?

<img width="788" alt="image" src="https://github.com/SheCodesAus/2024_a_dynamic_array_frontend/assets/16198398/9ae0610d-1339-470d-969c-296be08dce41">

2024-04-03 09:24 UTC, blakerach1 commented on src/components/NavBar/NavBar.jsx
1. Fixed, had my conditionals around the wrong way. 
2. Yeah profile page with GET functionality still under development. 


**Logged out view**
![Logged out view](https://github.com/SheCodesAus/2024_a_dynamic_array_frontend/assets/134209192/2c75e1e3-ec80-49f5-bbc0-2d5bfed00643)

**user with profile not admin**
![user with profile not admin](https://github.com/SheCodesAus/2024_a_dynamic_array_frontend/assets/134209192/38d86b50-276b-4abc-b052-399611b5e9ec)

**user no profile not admin**
![user no profile](https://github.com/SheCodesAus/2024_a_dynamic_array_frontend/assets/134209192/06f2b5d2-41dc-4e37-bbb5-383f71a83e3e)

**admin user with profile**
![admin user with profile](https://github.com/SheCodesAus/2024_a_dynamic_array_frontend/assets/134209192/74d9a28e-7bcb-468d-a519-83e60400121f)

2024-04-03 12:15 UTC, Lyndallh approved these changes

2024-04-03 12:19 UTC, merged