Fixed the footer height
SheCodesAus/2024_a_dynamic_array_frontend pull request #63
Opened 2024-04-02 13:42 UTC by Sahar-Kavousi

## Describe your changes

Fixed the height of the footer

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## What kind of feedback do you need?

Need a quick look

## Checklist:

- [x] I have performed a self-review of my code
- [ ] I have recommended where to start and how to proceed with the review
- [ ] I have done a git pull from DEV to ensure this PR is up to date

2024-04-02 23:10 UTC, shayzimm approved these changes

2024-04-02 23:34 UTC, Lyndallh requested changes

2024-04-02 23:34 UTC, Lyndallh commented on src/components/Footer/Footer.css
This look very sleek, but my understanding of Amy's feedback was that she wanted the "position:fixed" attribute removed on the footer. She mentioned the term 'fixed' and then must have remembered she was a supposed to be a non-technical client and said "i don't see why you can't just scroll to the bottom to find it - it is taking up a lot of real estate".

2024-04-03 02:32 UTC, Sahar-Kavousi commented on src/components/Footer/Footer.css
Yes, She mentioned dislike for the fixed footer, and I agree that we should reconsider it. If I find the time, I'll revisit it and make the necessary adjustments. For now, I've adjusted the footer height to improve its appearance. Removing the fixed position of the footer would impact the layout of all pages and would require a few hours to modify, but I'll consider it for future changes.

2024-04-03 03:27 UTC, Lyndallh approved these changes

2024-04-03 06:30 UTC, merged